export { default as CategoriasListPage } from './CategoriasListPage'
export { default as CategoriaFormPage } from './CategoriaFormPage'
export { default as CategoriaImagenUpload } from './CategoriaImagenUpload'
export { default as CategoriaInfoGeneral } from './CategoriaInfoGeneral'
export { default as CategoriesList } from './CategoriesList'
